### ISSUE TITLE
Demos Not Brought Over

### ISSUE THREAD

**Issue by torgo** [SamsungInternet/blog#36]
**Describe the problem**
Some of the demos which were previously accessible under samsunginter.net are no longer accessible.

**To Reproduce**
How do we replicate this? Tell us:
...@diekus to provide more detail...

**Checklist before submitting**
- [X] I have checked the list of issues (open and closed) on this repository and this issue has not been reported.
- [X] I have selected the **DevHub Issue Board** under the **Projects** assignment (right of the page).

**Comment by AdaRoseCannon** [comment]
Fixed
