### ISSUE TITLE
Ada's Rube Goldberg Article Not Ported to New Site

### ISSUE THREAD

**Issue by torgo** [SamsungInternet/blog#37]
**Describe the problem**
Ada wrote an article "A Rube Goldberg Machine" which was posted directly to the old site. It hasn't been brought over to the new site so some links are now broken. E.G. from https://css-tricks.com/rube-goldberg-machine/

**To Reproduce**
How do we replicate this? Tell us:
1. Go to : https://samsunginter.net/rube-goldberg-article/
2. see blank page

**Expected behavior**
See a lovely article.

**Checklist before submitting**
- [X] I have checked the list of issues (open and closed) on this repository and this issue has not been reported.
- [X] I have selected the **DevHub Issue Board** under the **Projects** assignment (right of the page).

**Comment by AdaRoseCannon** [comment]
Fixed.
